apiVersion: v1
type: Opaque
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
data:
  secretkey: QklwVk5QUm82ZVdKcTdEeDBnN3J4MXhPUGlsRG4xN1FmbVpxWTZnRUxSeUR0ODZUdEFzNzVGaDR1WEhFckNrRyBkK0s4ZWNGRWNMTXJlT3VZZU44RmFUOUttcDBjYlh2Z2ExUkxLT3ZPcnZ4R2RFTjJwemN2Q21OTEJIZFpxZVlKIEVmNk5IOEdJQXJaczFPYW8wV3dXeFJJN1Q4VkJ2QmFBWU5QWGk5Z0xQVTQ9

