apiVersion: v1
kind: Service
metadata:
  namespace: ingress-nginx
  name: my-nginx
  labels:
    run: my-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: hello-world
---
apiVersion: networking.k8s.io/v1beta1 
kind: Ingress
metadata:
  namespace: ingress-nginx
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /testpath
        backend:
          serviceName: my-nginx
          servicePort: 80